### ISSUE TITLE
🏄 Apply RSR v0.11.0

### ISSUE THREAD

**Issue by in4s** [j4s/superglobals#66]
- [x] !!!!! edit namespace j4s/superglobals
- [x] Add milestone 🏄 Apply RSR v0.11.0
- [x] Add this issue
- [x] Pin this issue
- [x] Edit label enhancement set color code #16C60C
- [x] Add label gitflowM with color code #FFB900
- [x] Add label test with color code #0366d6
- [x] Add label canProceed with color code #5319e7
- [x] Add label refactoring with color code #CCCCCC
- [x] Add label Urgent with color code #b60205
- [x] Make this issue pinned to the left
- [x] In this milestone create issues with steps 2-13 of that process
    - [x] 2. Add branch develop [from_0.11.0](https://github.com/j4s/superglobals/issues/new/?milestone=🏄+Apply+RSR+v0.11.0&assignees=in4s&labels=gitflowM&title=🏄+RSR:+2.+Add+branch+develop&body=-+%5B+%5D+Set+up+or+check:%0D%0A+git+config+--global+user.name%0D%0A+git+config+--global+user.email%0D%0A+git+config+--global+core.eol+lf%0D%0A+git+config+--global+core.safecrlf+warn%0D%0A+git+config+--global+core.autocrlf+input%0D%0A-+%5B+%5D+Clone+repository+https://github.com/j4s/superglobals.git%0D%0A-+%5B+%5D+git+checkout+-b+develop%0D%0A-+%5B+%5D+add+README.md+file%0D%0A-+%5B+%5D+git+add+.%0D%0A-+%5B+%5D+git+commit+close+%232%0D%0A-+%5B+%5D+git+push)
    - [x] 3. [from_0.3.0](https://github.com/j4s/superglobals/issues/new/?milestone=🏄+Apply+RSR+v0.11.0&assignees=in4s&labels=gitflowM&title=🏄+RSR:+3.+Make+develop+default&body=-+[+]+Make+develop+default+branch+at+github%0A-+[+]+Remove+branch+master+at+github%0A-+[+]+Add+Branch+protection+rules:+develop,+++first+two+checkpoints%0A-+[+]+Remove+local+repository+folder%0A-+[+]+Clone+repository+https://github.com/j4s/superglobals.git%0A-+[+]+Check:+There+is+only+a+develop+branch+in+the+local+(no+other+branches))
    - [x] 4. [from_v0.11.0](https://github.com/j4s/superglobals/issues/new/?milestone=🏄+Apply+RSR+v0.11.0&assignees=in4s&labels=gitflowM&title=🏄+RSR:+4.+Add+template+files+to+repo&body=-+%5B+%5D+Copy+files+from+the+desired+template+folder%0D%0A-+%5B+%5D+Edit+---release-a-new-version.md+file+%28repo+name%29%0D%0A-+%5B+%5D+git+add+.%0D%0A-+%5B+%5D+git+commit+close+%233%2C+close+%234%0D%0A-+%5B+%5D+git+push%0D%0A-+%5B+%5D+Check:+Issues+3-4+are+closed)
    - [ ] 5. [from_0.1.0](https://github.com/j4s/superglobals/issues/new/?milestone=🏄+Apply+RSR+v0.11.0&assignees=in4s&labels=gitflowM&title=🏄+RSR:+5.+Add+current+project+files%2C+if+any&body=-+%5B+%5D+Copy+files+to+local+repo+folder%0D%0A-+%5B+%5D+git+add+.%0D%0A-+%5B+%5D+git+commit+close+%235%0D%0A-+%5B+%5D+git+push) (optional)
    - [ ] 6. [from_0.1.0](https://github.com/j4s/superglobals/issues/new/?milestone=🏄+Apply+RSR+v0.11.0&assignees=in4s&labels=gitflowM&title=🏄+RSR:+6.+Put+sftp-config.json+to+the+local+lib+folder&body=) (optional)
    - [ ] 7. [from_0.1.0](https://github.com/j4s/superglobals/issues/new/?milestone=🏄+Apply+RSR+v0.11.0&assignees=in4s&labels=gitflowM&title=🏄+RSR:+7.+Fix+namespaces+to+in4s+%28from+j4s%2C+47s+and+others%29&body=-+%5B+%5D+git+add+.%0D%0A-+%5B+%5D+git+commit+close+%236%2C+close+%237%0D%0A-+%5B+%5D+git+push) (optional)
    - [x] 8. [from_v0.11.0](https://github.com/j4s/superglobals/issues/new/?milestone=🏄+Apply+RSR+v0.11.0&assignees=in4s&labels=gitflowM&title=🏄+RSR:+8.+Edit+README.md%2C+Repository+description&body=-+%5B+%5D+Edit+Repository+description+add/edit+%28RSR+v0.11.0%29+at+the+end%0D%0A-+%5B+%5D+Edit+README.md:+Complies+with+standard+RSR+v0.11.0%0D%0A-+%5B+%5D+git+add+.%0D%0A-+%5B+%5D+git+commit+close+%238%0D%0A-+%5B+%5D+git+push)
    - [ ] 9. [from_0.1.0](https://github.com/j4s/superglobals/issues/new/?milestone=🏄+Apply+RSR+v0.11.0&assignees=in4s&labels=gitflowM&title=🏄+RSR:+9.+Release+version&body=) (optional)
    - [ ] 10. [from_0.1.0](https://github.com/j4s/superglobals/issues/new/?milestone=🏄+Apply+RSR+v0.11.0&assignees=in4s&labels=gitflowM&title=🏄+RSR:+10.+Test+new+released+version&body=) (optional)
    - [x] 11. [from_0.10.1](https://github.com/j4s/superglobals/issues/new/?milestone=🏄+Apply+RSR+v0.11.0&assignees=in4s&labels=gitflowM&title=🏄+RSR:+11.+Add+Collaborators+to+repository&body=-+%5B+%5D+Add+collaborators%0D%0A-+%5B+%5D+Add+issues+for+each+collaborator+by+the+link:+https://github.com/in4s/gitflow/issues/new%3Ftitle%3DAccept%2Binvitation%2Bto%2Bj4s/superglobals%2Brepository%2B*%26labels%3DgitflowM%2CcanProceed%2CUrgent%26body%3DConfirm%2Bit%2Bby%2Bthis%2Blink:%2Bhttps://github.com/j4s/superglobals/invitations) (optional)
    - [x] 12. [from_0.10.1](https://github.com/j4s/superglobals/issues/new/?milestone=🏄+Apply+RSR+v0.11.0&assignees=in4s&labels=gitflowM&title=🏄+RSR:+12.+Check+Confirm+Collaborators+to+repository&body=) (optional)
    - [ ] 13. [from_0.6.0](https://github.com/j4s/superglobals/issues/new/?milestone=🏄+Apply+RSR+v0.11.0&assignees=in4s&labels=gitflowM&title=🏄+RSR:+13.+Move+issues+from+bitbucket&body=) (optional)
- [x] Apply each step of this process to repository
- [x] Check closing issues for RSR process
- [x] Close milestone 🏄 Apply RSR v0.11.0
- [x] Close this issue
- [x] Unpin it
