### ISSUE TITLE
🏄 Apply RSR v0.13.4

### ISSUE THREAD

**Issue by in4s** [j4s/superglobals#79]
- [x] !!!!! edit namespace j4s/superglobals
- [x] Add milestone 🏄 Apply RSR v0.13.4
- [x] Pin this issue; Pin it to the left
- [ ] Add repo shorcut to webshortcuts
- [x] [Milestone](https://github.com/j4s/superglobals/milestones/new) and [Labels](https://github.com/j4s/superglobals/labels): (from_0.13.0)
    - [x] Add milestone 📚 Someday, Maybe
    - [ ] Edit label enhancement set color code #16C60C
    - [ ] Add label gitflowM with color code #FFB900
    - [ ] Add label canProceed with color code #5319e7
    - [ ] Add label Urgent with color code #b60205
    - [ ] Add label test with color code #0366d6
    - [ ] Add label refactoring with color code #CCCCCC
- [x] Create issues if their RSR version higher than current RSR version or the project
    - [x] 2. Git settings               [from_0.12.0](https://github.com/j4s/superglobals/issues/new/?milestone=🏄+Apply+RSR+v0.13.4&assignees=in4s&labels=gitflowM&title=🏄+RSR:+2.+Git+settings&body=-+%5B+%5D+Set+up+or+check:%0D%0A+git+config+--global+user.name%0D%0A+git+config+--global+user.email%0D%0A+git+config+--global+core.eol+lf%0D%0A+git+config+--global+core.safecrlf+warn%0D%0A+git+config+--global+core.autocrlf+input%0D%0A-+%5B+%5D+For+each+host+of+this+project+make+issue+Check+Git+Settings%0D%0A-+%5B+%5D+Clone+repository+https:%2F%2Fgithub.com%2Fj4s/superglobals.git%0D%0A-+%5B+%5D+git+checkout+-b+develop%0D%0A-+%5B+%5D+add+.gitignore+file+from+template+folder%0D%0A-+%5B+%5D+git+add+.+%2C+git+commit+close+%232%0D%0A-+%5B+%5D+git+push)
    - [ ] 3. Github settings            [from_0.3.0](https://github.com/j4s/superglobals/issues/new/?milestone=🏄+Apply+RSR+v0.13.4&assignees=in4s&labels=gitflowM&title=🏄+RSR%3A+3.+Github+settings&body=-+%5B+%5D+Make+develop+default+branch+at+github%0D%0A-+%5B+%5D+Remove+branch+master+at+github%0D%0A-+%5B+%5D+Add+Branch+protection+rules%3A+develop%2C+%2B+first+two+checkpoints+%28if+possible%29%0D%0A-+%5B+%5D+Remove+local+repository+folder+%28optional%29%0D%0A-+%5B+%5D+Clone+repository+https%3A%2F%2Fgithub.com%2Fj4s/superglobals.git+%28optional%29%0D%0A-+%5B+%5D+Check%3A+There+is+only+a+develop+branch+in+the+local+%28no+other+branches%29)
    - [x] 4. Add template files to repo [from_v0.13.4](https://github.com/j4s/superglobals/issues/new/?milestone=🏄+Apply+RSR+v0.13.4&assignees=in4s&labels=gitflowM&title=🏄+RSR%3A+4.+Add+template+files+to+repo&body=-+%5B+%5D+Add+local+branch+f4+%28or+current+issue+number%29%0D%0A-+%5B+%5D+Copy+files+from+the+desired+template+folder%0D%0A-+%5B+%5D+git+add+.+%2C+git+commit+%234+template+files+updated%0D%0A-+%5B+%5D+Edit+README.md+file+%28set+repo+name%29%0D%0A-+%5B+%5D+Edit+---release-a-new-version.md+file+%28edit+repo+name%29%0D%0A-+%5B+%5D+git+add+.+%2C+git+commit+close+%233%2C+close+%234%0D%0A-+%5B+%5D+%28CRMR%29+Create+pull+request%2C+Review+it%2C+Merge+it%2C+Remove+remote+branch%0D%0A-+%5B+%5D+Check%3A+Issues+3-4+are+closed%0D%0A-+%5B+%5D+Remove+local+branch)
    - [ ] 5. Add current project files  [from_0.1.0](https://github.com/j4s/superglobals/issues/new/?milestone=🏄+Apply+RSR+v0.13.4&assignees=in4s&labels=gitflowM&title=🏄+RSR%3A+5.+Add+current+project+files%2C+if+any&body=-+%5B+%5D+Add+local+branch+f5+%28or+current+issue+number%29%0D%0A-+%5B+%5D+Copy+files+to+the+local+repo+folder%0D%0A-+%5B+%5D+git+add+.+%2C+git+commit+close+%235%0D%0A-+%5B+%5D+%28CRMR%29+Create+pull+request%2C+Review+it%2C+Merge+it%2C+Remove+remote+branch%0D%0A-+%5B+%5D+Check%3A+Issue+5+is+closed%0D%0A-+%5B+%5D+Remove+local+branch)
    - [ ] 6. Put sftp-config.json ...   [from_0.1.0](https://github.com/j4s/superglobals/issues/new/?milestone=🏄+Apply+RSR+v0.13.4&assignees=in4s&labels=gitflowM&title=🏄+RSR:+6.+Put+sftp-config.json+to+the+local+lib+folder&body=) (optional)
    - [ ] 7. Fix namespaces to in4s     [from_0.1.0](https://github.com/j4s/superglobals/issues/new/?milestone=🏄+Apply+RSR+v0.13.4&assignees=in4s&labels=gitflowM&title=🏄+RSR%3A+7.+Fix+namespaces+to+in4s+%28from+j4s%2C+47s+and+others%29&body=-+%5B+%5D+Add+local+branch+f7+%28or+current+issue+number%29%0D%0A-+%5B+%5D+Make+changes+of+fixing+namespaces%0D%0A-+%5B+%5D+git+add+.+%2C+git+commit+close+%236%2C+close+%237%0D%0A-+%5B+%5D+%28CRMR%29+Create+pull+request%2C+Review+it%2C+Merge+it%2C+Remove+remote+branch%0D%0A-+%5B+%5D+Check%3A+Issues+6-7+are+closed%0D%0A-+%5B+%5D+Remove+local+branch) (optional)
    - [x] 8. Edit RSR version number    [from_v0.13.4](https://github.com/j4s/superglobals/issues/new/?milestone=🏄+Apply+RSR+v0.13.4&assignees=in4s&labels=gitflowM&title=🏄+RSR%3A+8.+Edit+README.md%2C+Repository+description&body=-+%5B+%5D+Edit+Repository+description+add%2Fedit+%28RSR+v0.13.4%29+at+the+end%0D%0A-+%5B+%5D+Add+local+branch+f8+%28or+current+issue+number%29%0D%0A-+%5B+%5D+Edit+README.md%3A+Complies+with+standard+RSR+v0.13.4%0D%0A-+%5B+%5D+git+add+.+%2C+git+commit+close+%238%0D%0A-+%5B+%5D+%28CRMR%29+Create+pull+request%2C+Review+it%2C+Merge+it%2C+Remove+remote+branch%0D%0A-+%5B+%5D+Check%3A+Issue+8+is+closed%0D%0A-+%5B+%5D+Remove+local+branch)
    - [ ] 9. Release version            [from_0.1.0](https://github.com/j4s/superglobals/issues/new/?milestone=🏄+Apply+RSR+v0.13.4&assignees=in4s&labels=gitflowM&title=🏄+RSR:+9.+Release+version&body=) (optional)
    - [ ] 10. Add Collaborators ...     [from_0.10.1](https://github.com/j4s/superglobals/issues/new/?milestone=🏄+Apply+RSR+v0.13.4&assignees=in4s&labels=gitflowM&title=🏄+RSR:+10.+Add+Collaborators+to+repository&body=-+%5B+%5D+Add+collaborators%0D%0A-+%5B+%5D+Add+issues+for+each+collaborator+by+the+link:+https://github.com/in4s/gitflow/issues/new%3Ftitle%3DAccept%2Binvitation%2Bto%2Bj4s/superglobals%2Brepository%2B*%26labels%3DgitflowM%2CcanProceed%2CUrgent%26body%3DConfirm%2Bit%2Bby%2Bthis%2Blink:%2Bhttps://github.com/j4s/superglobals/invitations) (optional)
    - [ ] 11. Check Confirm Collabor... [from_0.10.1](https://github.com/j4s/superglobals/issues/new/?milestone=🏄+Apply+RSR+v0.13.4&assignees=in4s&labels=gitflowM&title=🏄+RSR:+11.+Check+Confirm+Collaborators+to+repository&body=) (optional)
    - [ ] 12. Move issues from bitbucket [from_0.6.0](https://github.com/j4s/superglobals/issues/new/?milestone=🏄+Apply+RSR+v0.13.4&assignees=in4s&labels=gitflowM&title=🏄+RSR:+12.+Move+issues+from+bitbucket&body=) (optional)
- [x] Apply each step of this process to repository
- [x] Check closing issues for RSR process
- [x] Close milestone 🏄 Apply RSR v0.13.4
- [ ] Close this issue
- [ ] Unpin it
